project_name: human_body_segmentation
experiment_name: segmentation_baseline
track_in_clearml: true
trainer_config:
  min_epochs: 7
  max_epochs: 100
  check_val_every_n_epoch: 5
  log_every_n_steps: 20
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: false
  fast_dev_run: false
  default_root_dir: null
  detect_anomaly: false
data_config:
  dataset_name: pascal_parts_dataset
  img_size:
  - 224
  - 224
  batch_size: 32
  data_split:
  - 0.8
  - 0.2
  num_workers: 10
  pin_memory: true
