project_name: human_body_segmentation
experiment_name: segmentation_baseline
track_in_clearml: false
trainer_config:
  min_epochs: 7
  max_epochs: 50
  check_val_every_n_epoch: 5
  log_every_n_steps: 20
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: false
  fast_dev_run: false
  default_root_dir: null
  detect_anomaly: false
data_config:
  dataset_name: pascal_parts_dataset
  img_size:
  - 224
  - 224
  batch_size: 32
  data_split:
  - 0.8
  - 0.2
  num_workers: 10
  pin_memory: true
  prefetch_factor: 3
module_config:
  segm_kwargs:
    arch: FPN
    encoder_name: efficientnet-b0
  optimizer:
    target: torch.optim.AdamW
    kwargs:
      lr: 1e-3
  scheduler:
    target: src.schedulers.get_cosine_schedule_with_warmup
    kwargs:
      num_warmup_steps: 30
      num_cycles: 1.8
